CREATE DATABASE IF NOT EXISTS kob DEFAULT CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE kob;

-- 用户表
CREATE TABLE user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(200) NOT NULL,          -- 存储加密哈希
  photo VARCHAR(255) NULL,
  rating INT NOT NULL DEFAULT 1500,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Bot 表
CREATE TABLE bot (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(255) NULL,
  code TEXT NOT NULL,
  is_default TINYINT(1) NOT NULL DEFAULT 0,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_bot_user FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 对局记录
CREATE TABLE record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  player_a_id BIGINT NOT NULL,
  player_b_id BIGINT NOT NULL,
  player_a_bot_id BIGINT NULL,
  player_b_bot_id BIGINT NULL,
  map_data TEXT NOT NULL,
  steps_a TEXT NULL,
  steps_b TEXT NULL,
  result VARCHAR(20) NOT NULL,
  loser VARCHAR(20) NULL,
  record_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rec_user_a FOREIGN KEY (player_a_id) REFERENCES user(id),
  CONSTRAINT fk_rec_user_b FOREIGN KEY (player_b_id) REFERENCES user(id),
  CONSTRAINT fk_rec_bot_a  FOREIGN KEY (player_a_bot_id) REFERENCES bot(id),
  CONSTRAINT fk_rec_bot_b  FOREIGN KEY (player_b_bot_id) REFERENCES bot(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
